//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    
    [Flags]
    public enum AvailabilityType : int
    {
        AVAILABLE = 0,
        PENDING = 1,
        PENDING_BACKUP_ACCEPTED = 2,
        DELISTED = 3,
        SOLD = 4
    }
}
