//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    
    public enum ChangeType : int
    {
        Availability = 0,
        Status = 1,
        ListPrice = 2,
        OfferPrice = 3,
        Evaluation = 4,
        Created = 5,
        Edited = 6
    }
}
