//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    
    public enum DecisionStatusType : int
    {
        NOT_TO_OFFER = 0,
        TO_OFFER = 1,
        MAYBE = 2,
        NOTIFY_AGENT = 3,
        OFFERED = 4,
        OFFER_ACCEPTED = 5,
        BOUGHT = 6,
        REJECTED = 7,
        NOT_DECIDED = -1,
        UNABLE_TO_OFFER = 8,
        BACKED_OUT = 9
    }
}
