//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighbourhood
    {
        public Neighbourhood()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public int median_price { get; set; }
        public int rental { get; set; }
        public Nullable<decimal> p_r_rate { get; set; }
        public string url { get; set; }
        public int education { get; set; }
        public int educational_rating { get; set; }
        public decimal appreciation_1990 { get; set; }
        public decimal appreciation_10y { get; set; }
        public decimal appreciation_5y { get; set; }
        public decimal appreciation_2y { get; set; }
        public decimal appreciation_1y { get; set; }
        public decimal appreciation_1q { get; set; }
        public Nullable<decimal> appreciation_mean { get; set; }
        public int crime_index { get; set; }
        public decimal vacancy_ratio { get; set; }
        public Nullable<decimal> score_all { get; set; }
        public Nullable<decimal> score_investment { get; set; }
        public Nullable<decimal> score_mean { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
    }
}
