//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Comment
    {
        public System.Guid id { get; set; }
        public System.Guid property_id { get; set; }
        public int comments { get; set; }
        public System.DateTime updated_date { get; set; }
        public int updated_by { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual User User { get; set; }
    }
}
