//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Change_History
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> property_id { get; set; }
        public string change_content { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public System.DateTime updated_date { get; set; }
        public int updated_by { get; set; }
        public Nullable<ChangeType> change_type { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual User User { get; set; }
    }
}
