//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Rental_Tracking
    {
        public System.Guid id { get; set; }
        public System.Guid property_id { get; set; }
        public Nullable<int> rental_zrent { get; set; }
        public Nullable<int> rental_rentometer { get; set; }
        public Nullable<int> rental_zilpy { get; set; }
        public Nullable<int> rental_mean { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
