//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Sale
    {
        public System.Guid property_id { get; set; }
        public int price { get; set; }
        public SaleType type { get; set; }
        public int tax { get; set; }
        public decimal p_t_rate { get; set; }
        public AvailabilityType availability { get; set; }
        public Nullable<decimal> return_rate_mean { get; set; }
        public Nullable<int> cash_flow_mean { get; set; }
        public Nullable<decimal> score { get; set; }
        public Nullable<int> offer_price { get; set; }
        public Nullable<System.DateTime> offer_date { get; set; }
        public Nullable<DecisionStatusType> status { get; set; }
        public Nullable<int> initial_cash { get; set; }
        public string url_zillow { get; set; }
        public string url_redfin { get; set; }
        public string url_ziprealty { get; set; }
        public Nullable<int> list_fmv_diff { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> listing_date { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
