//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltairScope.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_FMV_Tracking
    {
        public System.Guid id { get; set; }
        public System.Guid property_id { get; set; }
        public Nullable<int> fmv_zestimate { get; set; }
        public Nullable<int> fmv_smartzip { get; set; }
        public Nullable<int> fmv_eappraisal { get; set; }
        public Nullable<int> fmv_homeseeker { get; set; }
        public Nullable<int> fmv_mean { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
